service: appointment-store

frameworkVersion: "4.9"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:    
  processMessage:
    handler: dist/src/adapters/lambdas/create-appointment-handler.app
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:841162699497:AppointmentSQSQueue
          batchSize: 1       

   


custom:
  esbuild:
    configFile: ./esbuild.config.js 

package:
  individually: true
  include:
    - dist/**
    - package.json
